// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypnstfoxeddpicryhxhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwbnN0Zm94ZWRkcGljcnloeGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MDU2NDEsImV4cCI6MjA3NjM4MTY0MX0.3lbb_jyZML0nBQD0mMxGrr6xnbIFIYiI0FFiHnTrVbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});